name: Deploy to Docker Hub

on:
  push:
    branches:
      - master  # Triển khai khi code được gộp vào nhánh deploy
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/xdhv:latest .

      # 4. Push Docker image lên Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/xdhv:latest

      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}  # Lưu địa chỉ IP/hostname của server SSH trong Secrets
          username: ${{ secrets.SSH_USERNAME }}  # Lưu username của server SSH trong Secrets
          password: ${{ secrets.SSH_PASSWORD }}  # Lưu password của server SSH trong Secrets hoặc sử dụng private key
          port: 22  # Cổng SSH (mặc định là 22)
          script: |
            docker pull karzix/xdhv:latest

            docker stop xdhv-container  || true
            docker rm xdhv-container  || true

            docker run -d --name xdhv-container --restart unless-stopped -p 3000:8080 karzix/xdhv:latest

            docker image prune -a -f
